2025-02-23 18:01:58,566 INFO    MainThread:3988538 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-23 18:01:58,566 INFO    MainThread:3988538 [wandb_setup.py:_flush():67] Configure stats pid to 3988538
2025-02-23 18:01:58,566 INFO    MainThread:3988538 [wandb_setup.py:_flush():67] Loading settings from /home/x_tuhan/.config/wandb/settings
2025-02-23 18:01:58,566 INFO    MainThread:3988538 [wandb_setup.py:_flush():67] Loading settings from /proj/berzelius-2024-336/users/x_tuhan/garage/quantizedSAE/ternary_sae/wandb/settings
2025-02-23 18:01:58,566 INFO    MainThread:3988538 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-23 18:01:58,567 INFO    MainThread:3988538 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /proj/berzelius-2024-336/users/x_tuhan/garage/quantizedSAE/ternary_sae/wandb/run-20250223_180158-u52nquzl/logs/debug.log
2025-02-23 18:01:58,567 INFO    MainThread:3988538 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /proj/berzelius-2024-336/users/x_tuhan/garage/quantizedSAE/ternary_sae/wandb/run-20250223_180158-u52nquzl/logs/debug-internal.log
2025-02-23 18:01:58,567 INFO    MainThread:3988538 [wandb_init.py:init():761] calling init triggers
2025-02-23 18:01:58,567 INFO    MainThread:3988538 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'input_dim': 512, 'hidden_dim': 512, 'epochs': 1, 'lr': 0.001, 'sparsity_lambda': 0.0001, 'batch_size': 128, '_wandb': {}}
2025-02-23 18:01:58,567 INFO    MainThread:3988538 [wandb_init.py:init():784] starting backend
2025-02-23 18:01:58,567 INFO    MainThread:3988538 [wandb_init.py:init():788] sending inform_init request
2025-02-23 18:01:59,809 INFO    MainThread:3988538 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-23 18:01:59,810 INFO    MainThread:3988538 [wandb_init.py:init():803] backend started and connected
2025-02-23 18:01:59,813 INFO    MainThread:3988538 [wandb_init.py:init():896] updated telemetry
2025-02-23 18:02:01,345 INFO    MainThread:3988538 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-23 18:02:01,564 INFO    MainThread:3988538 [wandb_init.py:init():995] starting run threads in backend
2025-02-23 18:02:01,731 INFO    MainThread:3988538 [wandb_run.py:_console_start():2377] atexit reg
2025-02-23 18:02:01,732 INFO    MainThread:3988538 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-23 18:02:01,732 INFO    MainThread:3988538 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-23 18:02:01,733 INFO    MainThread:3988538 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-23 18:02:01,737 INFO    MainThread:3988538 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-23 18:02:04,057 INFO    MainThread:3988538 [wandb_watch.py:_watch():71] Watching
2025-02-23 18:02:08,690 WARNING MsgRouterThr:3988538 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/x_tuhan/.pyenv/versions/3.9.7/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/x_tuhan/.pyenv/versions/3.9.7/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/x_tuhan/.pyenv/versions/3.9.7/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/x_tuhan/.pyenv/versions/3.9.7/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/x_tuhan/.pyenv/versions/3.9.7/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-23 18:02:08,693 INFO    MsgRouterThr:3988538 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
